### ISSUE TITLE
Implementation Stage

### ISSUE THREAD

**Issue by vedattt** [cs102-project/LabConnect#9]
Any **GENERAL** discussion concerning the backend code for the project can go under here. Specific issues may, well, get their own separate _issue_ opened.

The milestone will most likely be changed to checkpoint 2 down the line, so that we can keep things in one place.
(Or it may not, who knows)

**Comment by berkan-sahin** [comment]
I think we are (finally) done with the design of the backend, with 8nly the occasional bugfix being left. If only we used this issue, or knew how to properly design a backend before the Great Refactoring. Anyways, cheers (or cheems)
